name: Build

on:
  push:
  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.ref }}

      - name: Set up corresponding JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ github.ref == 'refs/heads/1.21.1' && '21' ||
            github.ref == 'refs/heads/1.20.6' && '21' ||
            github.ref == 'refs/heads/1.20.1' && '17' ||
            github.ref == 'refs/heads/1.19.4' && '17' ||
            github.ref == 'refs/heads/1.18.2' && '17' ||
            github.ref == 'refs/heads/1.17.1' && '16' ||
            '8' }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build